#!/usr/bin/env bash
set -eu

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $dir

cargo_name="$(cat Cargo.toml | grep -m1 'name = ' | cut -d'"' -f2)"

export RUST_LOG=$cargo_name=debug

nodemon -e rs --ignore target --exec "cargo test $@"
