#!/usr/bin/env bash
# run CI-like set of tests
set -eu

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$dir"

echo "==> check wasm32-unknown-unknown"
cargo check --target wasm32-unknown-unknown --target-dir "${CARGO_TARGET_DIR:-./target}/wasm/"
echo "==> test"
cargo test
cargo test --benches
#echo "==> test (32-bit)"
#cargo test --target i686-unknown-linux-musl --target-dir "${CARGO_TARGET_DIR:-./target}/32bit/"
echo "==> rustfmt"
cargo fmt -- --check
