name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: rustup update stable
    - uses: actions/checkout@v2
    - run: cargo test
    - run: cargo test --benches

  ## TODO fix?
  # test_32bit:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - run: rustup update stable
  #   - run: sudo apt update && sudo apt install -yq gcc-multilib musl-tools
  #   - run: rustup target add i686-unknown-linux-musl
  #   - uses: actions/checkout@v2
  #   - run: cargo test --target i686-unknown-linux-musl

  check_wasm:
    runs-on: ubuntu-latest
    steps:
    - run: rustup update stable
    - run: rustup target add wasm32-unknown-unknown
    - uses: actions/checkout@v2
    - run: cargo check --target wasm32-unknown-unknown

  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - run: rustup update stable
    - uses: actions/checkout@v2
    - run: cargo fmt -- --check
